//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.488
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDF.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] huffmantree {
            get {
                object obj = ResourceManager.GetObject("huffmantree", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anti-Admin:
        ///
        ///Notrufe
        ///Botkontrollen
        ///
        ///Normale:
        ///
        ///API-Benötigt
        ///Programmname
        ///Programmersteller
        ///Downloadlink
        ///Website/Forenthread
        ///Version
        ///HWID
        ///
        ///Zeitpunkte:
        ///
        ///Bei Notruf --&gt; HWID, NR-Hash, Beschwerdeführer
        ///Bei Botkontrolle --&gt; HWID, Antwort, Admin
        ///Bei erfolgreichem Login --&gt; HWID, LoginDone, Antwortzeit
        ///Bei Instanzierung --&gt; HWID, Programmname, API ja/nein, Programmhash
        ///				  --&gt; Autor, Version, Downloadseite, Releaseseite, Supportseite ähnelt.
        /// </summary>
        public static string KDFApi {
            get {
                return ResourceManager.GetString("KDFApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -1433948737;20;PROTOCOL_HASH;CONFIRM_PROTOCOL_HASH;PROTOCOL_CONFIRMED;PROTOCOL_DATA;CHANGE_PROTOCOL;TEXT;CMD;LABEL;CHANNEL_NAME;IMAGE;SOUND;NICK;TITLE;INT_TIME_MILLIS;TIMEOUT_SECONDS;DURATION;INTERVAL;RED;GREEN;BLUE;COLOR;FONTSIZE;INT_ID;INT_HASH;INT_VALUE;SHORT_ID;STRING_ID;VALID;SELECTED;FOCUS;SHORT_TIME_MILLIS;DEFAULT_COLOR;DEFAULT_FONTSIZE;TEXTPANELTEXT;STRING_MAP;CONFIG;STRING_MAP_ENTRY;STRING_KEY;STRING_VALUE;MOUSEX;MOUSEY;EVENT_ID;WINDOW_ID;EVENT;TEXT_COLOR;BACKGROUND_COLOR;TOP_FADE_FROM;MIDDLE_FADE_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string module {
            get {
                return ResourceManager.GetString("module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die html, body 
        ///{
        ///	width:100%;
        ///	height:100%;
        ///}
        ///
        ///#ContentContainer
        ///{
        ///	width:100%;
        ///	height:100%;
        ///	position:absolute;
        ///	overflow:auto;
        ///	z-index:1;
        ///	background:transparent;
        ///}
        ///
        ///#background
        ///{
        ///	position:absolute;
        ///	z-index:-1;
        ///	width:100%;
        ///	height:100%;
        ///}
        ///
        ///body
        ///{
        ///	 /*background-color: &lt;bgcolor&gt;;*/	 
        ///	 background-repeat: no-repeat;
        ///	 background-position:center center;
        ///	 background-attachment: fixed;
        ///	 /*color: &lt;foreColor&gt;;*/
        ///	 font-family: Arial;
        ///	 /*font-size: &lt;fontSize&gt;;*/
        ///	 letter-spac [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string stylesheet {
            get {
                return ResourceManager.GetString("stylesheet", resourceCulture);
            }
        }
    }
}
